version: '3.7'

services:
  ba-nginx:
    image: nginx:alpine
    container_name: ba-nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./config/nginx/ssl:/etc/nginx/ssl
      - ./config/nginx/includes:/etc/nginx/includes
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./src/website:/var/www/website
      - ./src/website-beta:/var/www/website-beta
    networks:
      bondappetit:

  ba-ropsten:
    image: ethereum/client-go
    container_name: ba-ropsten
    restart: unless-stopped
    command: --datadir=/root/.ethereum --syncmode fast --ropsten --http --http.api "eth,net,web3" --http.corsdomain '*' --http.vhosts '*' --http.addr 0.0.0.0 --http.port 8545 --ws --ws.addr 0.0.0.0
    volumes:
      - ./data/ropsten:/root/.ethereum
    networks:
      bondappetit:

  ba-spy-ropsten:
    image: node:12-alpine
    container_name: ba-spy-ropsten
    working_dir: /home/node/app
    restart: unless-stopped
    volumes:
      - ./src/blockchain-spy-ropsten:/home/node/app
      - ./config:/config
    command: /bin/sh -c "npm ci && npm run ropsten"
    networks:
      bondappetit:

  ba-spy-mainnet:
    image: node:12-alpine
    container_name: ba-spy-mainnet
    working_dir: /home/node/app
    restart: unless-stopped
    volumes:
      - ./src/blockchain-spy-mainnet:/home/node/app
      - ./config:/config
    command: /bin/sh -c "npm ci && npm run start"
    networks:
      bondappetit:

  ba-ganache-ropsten:
    image: trufflesuite/ganache-cli
    container_name: ba-ganache-ropsten
    working_dir: /home/node/app
    restart: unless-stopped
    volumes:
      - node_modules:/home/node/app/node_modules
      - ./config:/config
    entrypoint: "/config/wait-for.sh ba-ropsten:8545 -- node /app/ganache-core.docker.cli.js -f http://ba-ropsten:8545 -m 'tape total toast night perfect myself kiwi rich glow moment bitter actual spare bottom boss' -h 0.0.0.0 -u 0x9403932015576D13Fb26B135ed7a35d5d95C18d4 -i 3 --chainId 3"
    networks:
      bondappetit:

  ba-ganache-mainnet:
    image: trufflesuite/ganache-cli
    container_name: ba-ganache-mainnet
    working_dir: /home/node/app
    restart: unless-stopped
    volumes:
      - node_modules:/home/node/app/node_modules
      - ./config:/config
    entrypoint: "/config/wait-for.sh ba-mainnet:8545 -- node /app/ganache-core.docker.cli.js -f http://ba-mainnet:8545 -m 'tape total toast night perfect myself kiwi rich glow moment bitter actual spare bottom boss' -h 0.0.0.0 -u 0x9403932015576D13Fb26B135ed7a35d5d95C18d4 -i 1 --chainId 1"
    networks:
      bondappetit:

  ba-website-cache:
    image: node:12-alpine
    container_name: ba-website-cache
    working_dir: /home/node/app
    restart: unless-stopped
    volumes:
      - ./src/website-cache:/home/node/app
      - ./config/website-cache.env:/home/node/app/.env
      - ./config:/config
    command: /bin/sh -c "npm ci && npm run build && npm run start"
    networks:
      bondappetit:

  ba-postgres:
    image: postgres:12.1
    container_name: ba-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: development
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: bondappetit
      PGDATA: /data/postgres
    volumes:
      - ./data/postgres:/data/postgres
    networks:
      bondappetit:

  ba-prerender:
    image: tvanro/prerender-alpine
    container_name: ba-prerender
    restart: unless-stopped
    environment:
      - MEMORY_CACHE=0
      - CACHE_MAXSIZE=1000
      - CACHE_TTL=6000
    networks:
      bondappetit:

volumes:
  node_modules:

networks:
  bondappetit:
