version: '3.7'

services:
  ba-nginx:
    image: nginx:alpine
    container_name: ba-nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d:cached
      - ./config/nginx/ssl:/etc/nginx/ssl:cached
      - ./config/nginx/includes:/etc/nginx/includes:cached
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:cached
    networks:
      bondappetit:

  ba-ropsten:
    image: ethereum/client-go
    container_name: ba-ropsten
    command: --datadir=/root/.ethereum/ropsten --syncmode fast --ropsten --http --http.api "eth,net,web3" --http.corsdomain '*' --http.vhosts '*' --http.addr 0.0.0.0 --http.port 8545 --ws
    volumes:
      - ./data/ropsten:/root/.ethereum/ropsten
    networks:
      bondappetit:

  ba-mainnet:
    image: ethereum/client-go
    container_name: ba-mainnet
    command: --datadir=/root/.ethereum/mainnet --syncmode fast --http --http.api "eth,net,web3" --http.corsdomain '*' --http.vhosts '*' --http.addr 0.0.0.0 --http.port 8545 --ws
    volumes:
      - ./data/mainnet:/root/.ethereum/mainnet
    networks:
      bondappetit:

networks:
  bondappetit:
