version: '3.7'

services:
  ba-nginx:
    image: nginx:alpine
    container_name: ba-nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d:cached
      - ./config/nginx/ssl:/etc/nginx/ssl:cached
      - ./config/nginx/includes:/etc/nginx/includes:cached
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:cached
    networks:
      bondappetit:

  ba-ropsten:
    image: ethereum/client-go
    container_name: ba-ropsten
    restart: unless-stopped
    command: --datadir=/root/.ethereum --syncmode fast --ropsten --http --http.api "eth,net,web3" --http.corsdomain '*' --http.vhosts '*' --http.addr 0.0.0.0 --http.port 8545 --ws --ws.addr 0.0.0.0
    volumes:
      - ./data/ropsten:/root/.ethereum
    networks:
      bondappetit:

  ba-mainnet:
    image: ethereum/client-go
    container_name: ba-mainnet
    restart: unless-stopped
    command: --datadir=/root/.ethereum --syncmode fast --http --http.api "eth,net,web3" --http.corsdomain '*' --http.vhosts '*' --http.addr 0.0.0.0 --http.port 8545 --ws --ws.addr 0.0.0.0
    volumes:
      - ./data/mainnet:/root/.ethereum
    networks:
      bondappetit:

  ba-spy-ropsten:
    image: node:12-alpine
    container_name: ba-spy-ropsten
    working_dir: /home/node/app
    restart: unless-stopped
    volumes:
      - ./src/blockchain-spy:/home/node/app
      - node_modules:/home/node/app/node_modules
      - ./config/services/blockchain-spy-ropsten.json:/home/node/app/config.json
      - ./config:/config
    command: "/config/wait-for.sh ba-ropsten:8546 -- npm run start"
    networks:
      bondappetit:

  ba-ganashe-ropsten:
    image: node:12-alpine
    container_name: ba-spy-ropsten
    working_dir: /home/node/app
    restart: unless-stopped
    volumes:
      - node_modules:/home/node/app/node_modules
      - ./config/services/blockchain-spy-ropsten.json:/home/node/app/config.json
      - ./config:/config
    command: "/config/wait-for.sh ba-ropsten:8545 -- /config/services/ganache-ropsten.run.sh"
    networks:
      bondappetit:

volumes:
  node_modules:

networks:
  bondappetit:
